---

- hosts: bastion
  become: yes
  become_user: root

  roles:

    - role: common
      papertrail_url: "{{ vars_papertrail_url }}"
      collect_metrics_from: "{{ global_collect_metrics_from }}"
      sudo_users: "{{ global_sudo_users }}"
      unprivileged_users:
        - joshua  # docsrs.infra.rust-lang.org
        - syphar  # docsrs.infra.rust-lang.org
        - nemo157  # docsrs.infra.rust-lang.org
        - guillaumegomez  # docsrs.infra.rust-lang.org
        - shep  # play.rust-lang.org
        - technetos  # RDS access to the discord-mods-bot database
        - rylev # RDS access to rustc-perf
        - kobzol # RDS access to bors

    - role: datadog.datadog
      vars:
        datadog_api_key: "{{ vars_datadog_api_key }}"
        datadog_site: "datadoghq.com"

        datadog_config:
          tags:
            - "env:{{ vars_environment }}"
            - "service:bastion"
          process_config:
            enabled: "true"

    - role: bastion
