---

- hosts: playground
  become: yes
  become_user: root

  roles:

    - role: common
      papertrail_url: "{{ vars_papertrail_url }}"
      collect_metrics_from: "{{ global_collect_metrics_from }}"
      sudo_users: "{{ global_sudo_users + vars_extra_sudo_users }}"
      avoid_removing_docker_users:
        - playground

    - role: datadog.datadog
      tags:
        - monitoring
      vars:
        datadog_api_key: "{{ vars_datadog_api_key }}"
        datadog_site: "datadoghq.com"

        datadog_config:
          tags:
            - "env:{{ vars_environment }}"
            - "service:playground"
          process_config:
            enabled: "true"

    - role: letsencrypt
      dummy_certs: "{{ vars_letsencrypt_dummy_certs }}"
      email: admin@rust-lang.org
      domains:
        - "{{ inventory_hostname }}"

    - role: nginx
      worker_connections: "{{ vars_playground_number_connections }}"
      proxied:
        - domain: "{{ inventory_hostname }}"
          to: "http://127.0.0.1:{{ vars_playground_env_ui_port }}"
          websockets:
            - '/websocket'
          extra_locations:
            - path: '/docker-metrics'
              to: 'http://127.0.0.1:9323/metrics'

    - role: playground
      tags:
        - application
